-- Built-in templates are product contracts. Their control edges must be
-- explicit and conditional routes must carry the boolean output that chose
-- the route; otherwise a condition can visually branch but execute both ends.

UPDATE automation_workflow_template
SET definition = $pending$
{"globalVariables":{},"nodes":[
{"id":"start","type":"start","position":{"x":220,"y":180},"nodeMeta":{"title":"开始","icon":"▶","description":"工作流触发入口","color":"#10b981","category":"特殊节点"},"inputs":[],"outputs":[{"name":"trigger","valueType":"object","description":""}],"config":{}},
{"id":"search","type":"trackflow-issue-search","position":{"x":520,"y":180},"nodeMeta":{"title":"查找待办需求","icon":"🔍","description":"查询执行身份可访问的待办工单","color":"#0ea5e9","category":"TrackFlow"},"inputs":[{"name":"projectId","valueType":"number","required":false,"description":"","optional":false,"value":{"type":"ref","nodeId":"start","outputName":"trigger","path":"projectId"}},{"name":"statusIds","valueType":"string","required":false,"description":"","optional":false,"value":null},{"name":"priority","valueType":"string","required":false,"description":"","optional":false,"value":null},{"name":"issueType","valueType":"string","required":false,"description":"","optional":false,"value":null},{"name":"tagIds","valueType":"string","required":false,"description":"","optional":false,"value":null},{"name":"savedQueryId","valueType":"number","required":false,"description":"","optional":true,"value":null},{"name":"keyword","valueType":"string","required":false,"description":"","optional":true,"value":null},{"name":"assignedToMe","valueType":"boolean","required":false,"description":"","optional":true,"value":null},{"name":"sort","valueType":"string","required":false,"description":"","optional":true,"value":null},{"name":"limit","valueType":"number","required":false,"description":"","optional":true,"value":{"type":"literal","value":20}}],"outputs":[{"name":"issues","valueType":"array","description":""},{"name":"count","valueType":"number","description":""},{"name":"hasWork","valueType":"boolean","description":""}],"config":{}},
{"id":"has-work","type":"condition","position":{"x":820,"y":180},"nodeMeta":{"title":"有待处理工单？","icon":"❓","description":"根据搜索结果选择分支","color":"#f59e0b","category":"控制流"},"inputs":[{"name":"value","valueType":"any","required":true,"description":"","optional":false,"value":{"type":"ref","nodeId":"search","outputName":"hasWork"}}],"outputs":[{"name":"true","valueType":"boolean","description":""},{"name":"false","valueType":"boolean","description":""}],"config":{"operator":"equals","compareValue":"true"}},
{"id":"work-found","type":"end","position":{"x":1120,"y":100},"nodeMeta":{"title":"结束（存在待办）","icon":"⏹","description":"流程结束","color":"#ef4444","category":"特殊节点"},"inputs":[{"name":"result","valueType":"any","required":false,"description":"","optional":false,"value":{"type":"ref","nodeId":"has-work","outputName":"true"}}],"outputs":[],"config":{}},
{"id":"no-work","type":"end","position":{"x":1120,"y":260},"nodeMeta":{"title":"结束（无待办）","icon":"⏹","description":"流程结束","color":"#ef4444","category":"特殊节点"},"inputs":[{"name":"result","valueType":"any","required":false,"description":"","optional":false,"value":{"type":"ref","nodeId":"has-work","outputName":"false"}}],"outputs":[],"config":{}}
],"edges":[{"id":"start-search-flow","sourceNodeId":"start","sourcePortName":"__flow","targetNodeId":"search","targetPortName":"__flow"},{"id":"search-condition-data","sourceNodeId":"search","sourcePortName":"hasWork","targetNodeId":"has-work","targetPortName":"value"},{"id":"search-condition-flow","sourceNodeId":"search","sourcePortName":"__flow","targetNodeId":"has-work","targetPortName":"__flow"},{"id":"condition-work-flow","sourceNodeId":"has-work","sourcePortName":"__flow","targetNodeId":"work-found","targetPortName":"__flow","flowBranch":"true"},{"id":"condition-empty-flow","sourceNodeId":"has-work","sourcePortName":"__flow","targetNodeId":"no-work","targetPortName":"__flow","flowBranch":"false"}]}
$pending$
WHERE is_builtin IS TRUE AND sort_order = 1;

UPDATE automation_workflow_template
SET definition = $approval$
{"globalVariables":{},"nodes":[
{"id":"start","type":"start","position":{"x":220,"y":180},"nodeMeta":{"title":"开始","icon":"▶","description":"工作流触发入口","color":"#10b981","category":"特殊节点"},"inputs":[],"outputs":[{"name":"trigger","valueType":"object","description":""}],"config":{}},
{"id":"approval","type":"approval","position":{"x":560,"y":180},"nodeMeta":{"title":"人工审批","icon":"🛡","description":"暂停并等待审批结果","color":"#dc2626","category":"控制流"},"inputs":[{"name":"title","valueType":"string","required":true,"description":"","optional":false,"value":{"type":"literal","value":"确认执行自动化操作"}},{"name":"description","valueType":"string","required":false,"description":"","optional":false,"value":{"type":"literal","value":"请确认本次自动化请求的输入和影响范围。"}},{"name":"payload","valueType":"object","required":false,"description":"","optional":false,"value":{"type":"ref","nodeId":"start","outputName":"trigger"}}],"outputs":[{"name":"approved","valueType":"boolean","description":""},{"name":"rejected","valueType":"boolean","description":""},{"name":"comment","valueType":"string","description":""}],"config":{"riskLevel":"medium","expiryHours":24}},
{"id":"approved-end","type":"end","position":{"x":900,"y":100},"nodeMeta":{"title":"结束（批准）","icon":"⏹","description":"流程结束","color":"#ef4444","category":"特殊节点"},"inputs":[{"name":"result","valueType":"any","required":false,"description":"","optional":false,"value":{"type":"ref","nodeId":"approval","outputName":"approved"}}],"outputs":[],"config":{}},
{"id":"rejected-end","type":"end","position":{"x":900,"y":260},"nodeMeta":{"title":"结束（拒绝）","icon":"⏹","description":"流程结束","color":"#ef4444","category":"特殊节点"},"inputs":[{"name":"result","valueType":"any","required":false,"description":"","optional":false,"value":{"type":"ref","nodeId":"approval","outputName":"rejected"}}],"outputs":[],"config":{}}
],"edges":[{"id":"start-approval-data","sourceNodeId":"start","sourcePortName":"trigger","targetNodeId":"approval","targetPortName":"payload"},{"id":"start-approval-flow","sourceNodeId":"start","sourcePortName":"__flow","targetNodeId":"approval","targetPortName":"__flow"},{"id":"approval-approved-flow","sourceNodeId":"approval","sourcePortName":"__flow","targetNodeId":"approved-end","targetPortName":"__flow","flowBranch":"approved"},{"id":"approval-rejected-flow","sourceNodeId":"approval","sourcePortName":"__flow","targetNodeId":"rejected-end","targetPortName":"__flow","flowBranch":"rejected"}]}
$approval$
WHERE is_builtin IS TRUE AND sort_order = 2;

UPDATE automation_workflow_template
SET definition = $delay$
{"globalVariables":{},"nodes":[
{"id":"start","type":"start","position":{"x":220,"y":180},"nodeMeta":{"title":"开始","icon":"▶","description":"工作流触发入口","color":"#10b981","category":"特殊节点"},"inputs":[],"outputs":[{"name":"trigger","valueType":"object","description":""}],"config":{}},
{"id":"delay","type":"delay","position":{"x":560,"y":180},"nodeMeta":{"title":"延时等待","icon":"⏱","description":"暂停五秒后继续","color":"#64748b","category":"控制流"},"inputs":[{"name":"duration","valueType":"number","required":false,"description":"","optional":false,"value":{"type":"literal","value":5}}],"outputs":[{"name":"done","valueType":"boolean","description":""}],"config":{"seconds":5}},
{"id":"end","type":"end","position":{"x":900,"y":180},"nodeMeta":{"title":"结束","icon":"⏹","description":"流程结束","color":"#ef4444","category":"特殊节点"},"inputs":[{"name":"result","valueType":"any","required":false,"description":"","optional":false,"value":{"type":"ref","nodeId":"delay","outputName":"done"}}],"outputs":[],"config":{}}
],"edges":[{"id":"start-delay-flow","sourceNodeId":"start","sourcePortName":"__flow","targetNodeId":"delay","targetPortName":"__flow"},{"id":"delay-end-flow","sourceNodeId":"delay","sourcePortName":"__flow","targetNodeId":"end","targetPortName":"__flow"}]}
$delay$
WHERE is_builtin IS TRUE AND sort_order = 3;
